baseURL: "https://ITworksconsulting.co/"
theme: "up-business-theme"
languageCode: "en-us"

title: "ITworks Consulting"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "ITworks Consulting"
  description: "We’re your partner in IT and business growth. Learn more about our IT solutions by talking to one of our experts."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "Woluwe Saint Lambert, Brussels 1200"

  contact:
    - "nitish.verma@itwc.eu"
    - "+32-465 96 1874"

  copyright: "© 2023 ITWC All Rights Reserved"

  postProcess: false

menus:
  # main:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Let's connect"
      url: "mailto:nitish.verma@itwc.eu"
      weight: 5
      pre: "btn btn-primary text-light"

  # footer:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

taxonomies:
  series: "series"
  tags: "tags"
